name = "VLF"
uuid = "86670905-cf5e-428e-a540-2b4c7cb2fe26"
authors = ["JamesMCannon"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
